# Generated by Django 4.2.11 on 2026-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetask',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='imagetask',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
