# Generated by Django 4.2.11 on 2026-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_imagetask_height_imagetask_output_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetask',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='output_images/'),
        ),
    ]
